const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const DEFAULT_ADMIN_CREDENTIALS={username:'admin',password:'admin@123',name:'Admin',role:'Administrator'};
const DEFAULT_USERS=[
 {username:'hirun',password:'sync123',name:'Hirun Harshana',role:'Member',email:'hirun@syncboard.dev'},
 {username:'methul',password:'sync123',name:'Methul Demika',role:'Member',email:'methul@syncboard.dev'},
 {username:'disen',password:'sync123',name:'Disen Devmika',role:'Member',email:'disen@syncboard.dev'},
 {username:'nethushi',password:'sync123',name:'Nethushi Aloka',role:'Member',email:'nethushi@syncboard.dev'},
 {username:'hasini',password:'sync123',name:'Hasini Gunathilake',role:'Member',email:'hasini@syncboard.dev'},
 {username:'kaveesha',password:'sync123',name:'Kaveesha Navodi',role:'Member',email:'kaveesha@syncboard.dev'},
 
];
function normalizeUsername(name){return String(name).trim().toLowerCase().replace(/\s+/g,'.').replace(/[^a-z0-9.]/g,'')}
function repairUsers(users){
  if(!Array.isArray(users))return DEFAULT_USERS.map(u=>({...u,password:String(u.password||'sync123')}));
  return users.map((u,index)=>({
    ...u,
    username:String(u?.username||'').trim()||normalizeUsername(u?.name)||`member${index+1}`,
    password:String(u?.password||'sync123'),
    name:String(u?.name||'').trim()||String(u?.username||'').trim()||`Member ${index+1}`,
    role:u?.role||'Member',
    email:u?.email||''
  }));
}
const DEFAULT_MEMBERS=[
 {name:'Hirun Harshana',role:'UI/UX Designer',email:'Hirun@syncboard.dev',department:'Design'},
 {name:'Methul Demika',role:'Backend Developer',email:'Methul@syncboard.dev',department:'Engineering'},
 {name:'Disen Devmika',role:'Backend Developer',email:'Disen@syncboard.dev',department:'Engineering'},
 {name:'Nethushi.Aloka',role:'DevOps Engineer',email:'Nethushi@syncboard.dev',department:'Infrastructure'},
 {name:'Hasini Gunathilake',role:'Frontend Developer',email:'Hasini@syncboard.dev',department:'Engineering'},
 {name:'Kaveesha Navodi',role:'QA Engineer',email:'Kaveesha@syncboard.dev',department:'Quality'},

];
function getAdminCredentials(){return safeJSON(localStorage.getItem('syncboard-admin-credentials'),null)||DEFAULT_ADMIN_CREDENTIALS}
function saveAdminCredentials(creds){localStorage.setItem('syncboard-admin-credentials',JSON.stringify(creds))}
function getUsers(){
 const stored=safeJSON(localStorage.getItem('syncboard-users'),null);
 if(!stored){
   const defaults=repairUsers(DEFAULT_USERS);
   localStorage.setItem('syncboard-users',JSON.stringify(defaults));
   return defaults;
 }
 const repaired=repairUsers(stored);
 if(JSON.stringify(repaired)!==JSON.stringify(stored))localStorage.setItem('syncboard-users',JSON.stringify(repaired));
 return repaired;
}
function saveUsers(users){localStorage.setItem('syncboard-users',JSON.stringify(repairUsers(users)));publish('users')}
function getMemberUsers(){const members=getMembers();const users=[...getUsers()];members.forEach(member=>{let user=users.find(u=>u.name===member.name);if(!user){const base=normalizeUsername(member.name)||'member';let username=base;let counter=1;while(users.some(x=>x.username===username)){username=`${base}${counter++}`}user={username,password:'sync123',name:member.name,role:'Member',email:member.email||''};users.push(user)}else{user.name=member.name;user.email=member.email||user.email}});return users.filter(u=>members.some(m=>m.name===u.name))}
const INITIAL_TASKS=[
 {id:1,title:'Landing page UI',description:'Create responsive dashboard landing page.',assignee:'Hirun Harshana',status:'ongoing',progress:75,priority:'High',due:'2026-08-15',comments:['Responsive desktop section completed.']},
 {id:2,title:'API integration',description:'Connect task services to the client.',assignee:'Methul Demika',status:'assigned',progress:35,priority:'High',due:'2026-08-18',comments:['Waiting for endpoint confirmation.']},
 {id:3,title:'Database setup',description:'Prepare schema and sample project data.',assignee:'Disen Devmika',status:'ongoing',progress:90,priority:'Medium',due:'2026-08-12',comments:['Final migration test running.']},
 {id:4,title:'Authentication',description:'Create account/session flow.',assignee:'Nethushi.Aloka',status:'done',progress:100,priority:'High',due:'2026-08-10',comments:['Completed and reviewed.']},
 {id:5,title:'UI components',description:'Build reusable form and card components.',assignee:'Hasini Gunathilake',status:'done',progress:100,priority:'Medium',due:'2026-08-11',comments:['Reusable components complete.']},
 {id:6,title:'UI components',description:'Build reusable form and card components.',assignee:'Kaveesha Navodi',status:'done',progress:100,priority:'Medium',due:'2026-08-11',comments:['Reusable components complete.']}
];
function safeJSON(s,fallback){try{return JSON.parse(s)}catch{return fallback}}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function adminSession(){return safeJSON(sessionStorage.getItem('syncboard-admin'),null)||safeJSON(localStorage.getItem('syncboard-admin'),null)}
function getTasks(){let t=safeJSON(localStorage.getItem('syncboard-tasks'),null);if(!t){localStorage.setItem('syncboard-tasks',JSON.stringify(INITIAL_TASKS));return [...INITIAL_TASKS]}return t}
function saveTasks(t){localStorage.setItem('syncboard-tasks',JSON.stringify(t));publish('tasks')}
function getMembers(){return safeJSON(localStorage.getItem('syncboard-members'),null)||DEFAULT_MEMBERS}
function saveMembers(m){localStorage.setItem('syncboard-members',JSON.stringify(m));publish('members')}
function getNotifications(){return safeJSON(localStorage.getItem('syncboard-notifications'),null)||[]}
function getRequests(){return safeJSON(localStorage.getItem('syncboard-requests'),null)||[]}
function saveRequests(items){localStorage.setItem('syncboard-requests',JSON.stringify(items));publish('requests')}
function saveNotifications(n){localStorage.setItem('syncboard-notifications',JSON.stringify(n));publish('notifications')}
function getMemberLoginFor(memberName){return getMemberUsers().find(u=>u.name===memberName)||{username:'',password:''}}
function renderMemberLoginSettings(){const box=$('#memberLogins');if(!box)return;const members=getMembers();if(!members.length){box.innerHTML='<div class="muted small">No members available.</div>';return}box.innerHTML=`<div class="field"><label>Member</label><select id="memberLoginSelect">${members.map(m=>`<option value="${esc(m.name)}">${esc(m.name)}</option>`).join('')}</select></div><div class="field"><label>Login Username</label><input id="memberLoginUsername" placeholder="Username"></div><div class="field"><label>Login Password</label><input id="memberLoginPassword" type="password" placeholder="Password"></div><button class="btn" id="saveMemberLogin">Save member login</button><div class="small muted" style="margin-top:16px">Existing member logins:</div><div id="memberLoginList" class="member-login-list"></div>`;const select=$('#memberLoginSelect');if(select){select.addEventListener('change',populateMemberLoginFields)}$('#saveMemberLogin').onclick=saveMemberLogin;populateMemberLoginFields();renderMemberLoginList()}
function renderAdminSettings(){const creds=getAdminCredentials();$('#adminUsername').value=creds.username;$('#adminPassword').value=creds.password;renderMemberLoginSettings()}
function populateMemberLoginFields(){const member=$('#memberLoginSelect');if(!member)return;const user=getMemberLoginFor(member.value);$('#memberLoginUsername').value=user.username||'';$('#memberLoginPassword').value=user.password||''}
function renderMemberLoginList(){const list=$('#memberLoginList');if(!list)return;const users=getMemberUsers();if(!users.length){list.innerHTML='<div class="muted small">No member logins configured.</div>';return}list.innerHTML=users.map(u=>`<div class="panel"><strong>${esc(u.name)}</strong><div class="small">${esc(u.username)} · ${'•'.repeat(Math.max(4,String(u.password).length))}</div></div>`).join('')}
function saveAdminLogin(){const username=$('#adminUsername').value.trim(),password=$('#adminPassword').value;if(!username||!password){toast('Admin username and password are required');return}saveAdminCredentials({username,password,name:'Admin',role:'Administrator'});toast('Admin login updated')}
function saveMemberLogin(){const member=$('#memberLoginSelect')?.value;if(!member){toast('Select a member');return}const username=$('#memberLoginUsername').value.trim(),password=$('#memberLoginPassword').value.trim();if(!username||!password){toast('Username and password are required');return}const users=getUsers();const memberObj=getMembers().find(m=>m.name===member);const email=memberObj?.email||'';let user=users.find(u=>u.name===member);if(user){user.username=username;user.password=password;user.email=email}else{users.push({username,password,name:member,role:'Member',email})}const names=users.map(u=>normalizeUsername(u.username).toLowerCase());if(new Set(names).size!==names.length){toast('Member usernames must be unique');return}saveUsers(users);renderMemberLoginSettings();toast('Member login saved')}
function addNotification(recipient,title,message,type='admin'){const n=getNotifications();n.unshift({id:Date.now()+Math.random(),recipient,title,message,type,createdAt:new Date().toISOString(),readBy:[]});saveNotifications(n.slice(0,100))}
let channel=null;function getChannel(){if(!channel&&'BroadcastChannel' in window)channel=new BroadcastChannel('syncboard-live');return channel}function publish(kind){const c=getChannel();if(c)c.postMessage({type:'updated',kind,ts:Date.now()})}
function applyTheme(){document.body.classList.toggle('dark',localStorage.getItem('syncboard-theme')==='dark')}
function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('syncboard-theme',document.body.classList.contains('dark')?'dark':'light')}
function toast(m){let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function requireAdmin(){if(!adminSession()&&!location.pathname.endsWith('/admin/')&&!location.pathname.endsWith('/admin/index.html'))location.replace('index.html')}
function logoutAdmin(){sessionStorage.removeItem('syncboard-admin');localStorage.removeItem('syncboard-admin');location.href='index.html'}
function initLogin(){const f=$('#adminLoginForm');if(!f)return;if(adminSession()){location.replace('dashboard.html');return}const admin=getAdminCredentials();$('#togglePass')?.addEventListener('click',()=>{const p=$('#password');p.type=p.type==='password'?'text':'password'});f.addEventListener('submit',e=>{e.preventDefault();const u=$('#username').value.trim(),p=$('#password').value;if(u.toLowerCase()!==admin.username.toLowerCase()||p!==admin.password){$('#loginError').textContent='Invalid admin username or password.';return}const data={username:admin.username,name:admin.name,role:admin.role};($('#remember').checked?localStorage:sessionStorage).setItem('syncboard-admin',JSON.stringify(data));location.href='dashboard.html'})}
function initNav(){$$('[data-theme]').forEach(b=>b.onclick=toggleTheme);$$('[data-menu]').forEach(b=>b.onclick=()=>$('.sidebar')?.classList.toggle('open'));$$('[data-admin-logout]').forEach(b=>b.onclick=logoutAdmin)}
function initTopNotifications(){const themeBtn=$('[data-theme]');if(!themeBtn||$('#notificationButton'))return;const wrap=document.createElement('div');wrap.className='notification-wrap';wrap.innerHTML=`<button class="icon-btn notification-button" id="notificationButton" title="Notifications">🔔<span class="notification-count" id="notificationCount">0</span></button><div class="notification-popover" id="notificationPopover"><div class="notification-head"><strong>Admin Notifications</strong><button class="mini" id="markAdminRead">Mark all read</button></div><div class="notification-list" id="notificationList"></div></div>`;themeBtn.parentNode.insertBefore(wrap,themeBtn);$('#notificationButton').onclick=e=>{e.stopPropagation();$('#notificationPopover').classList.toggle('open');renderTopNotifications()};$('#markAdminRead').onclick=()=>{const n=getNotifications();n.forEach(x=>{if((x.recipient==='admin'||x.recipient==='all')&&!x.readBy.includes('admin'))x.readBy.push('admin')});saveNotifications(n);renderTopNotifications()};document.addEventListener('click',e=>{if(!wrap.contains(e.target))$('#notificationPopover')?.classList.remove('open')});renderTopNotifications()}
function renderTopNotifications(){const list=$('#notificationList'),count=$('#notificationCount');if(!list||!count)return;const items=getNotifications().filter(n=>n.recipient==='admin'||n.recipient==='all');const unread=items.filter(n=>!n.readBy.includes('admin')).length;count.textContent=unread;count.classList.toggle('hidden',!unread);list.innerHTML=items.length?items.slice(0,12).map(n=>`<div class="notification-item ${n.readBy.includes('admin')?'':'unread'}"><strong>${esc(n.title)}</strong><div>${esc(n.message)}</div><small>${new Date(n.createdAt).toLocaleString()}</small></div>`).join(''):'<div class="empty-note">No notifications yet.</div>'}
function statusBadge(s){return `<span class="badge ${s}">${s[0].toUpperCase()+s.slice(1)}</span>`}
function analytics(){const t=getTasks(),total=t.length,done=t.filter(x=>x.status==='done').length,ongoing=t.filter(x=>x.status==='ongoing').length,assigned=t.filter(x=>x.status==='assigned').length,avg=total?Math.round(t.reduce((a,x)=>a+Number(x.progress||0),0)/total):0,overdue=t.filter(x=>x.due&&new Date(x.due)<new Date()&&x.status!=='done').length;return {total,done,ongoing,assigned,avg,overdue}}
function renderStats(){const a=analytics();Object.entries({total:a.total,assigned:a.assigned,ongoing:a.ongoing,done:a.done}).forEach(([k,v])=>{const e=$(`[data-stat="${k}"]`);if(e)e.textContent=v})}
function renderDashboard(){if(!$('#dashboardChart'))return;const a=analytics(),t=getTasks();const vals=[a.avg,a.total?Math.round(a.done/a.total*100):0,a.total?Math.round(a.ongoing/a.total*100):0,a.total?Math.round(a.assigned/a.total*100):0];$('#dashboardChart').innerHTML=vals.map(n=>`<div class="bar" style="height:${Math.max(8,n)}%"><span class="small" style="position:absolute;top:-21px;left:50%;transform:translateX(-50%);color:var(--muted)">${n}%</span></div>`).join('');$('#analyticsSummary').innerHTML=`<div class="analytics-stack"><div class="analytics-card"><span>Average progress</span><strong>${a.avg}%</strong></div><div class="analytics-card"><span>Completed</span><strong>${a.done}/${a.total}</strong></div><div class="analytics-card"><span>Ongoing</span><strong>${a.ongoing}</strong></div><div class="analytics-card"><span>Overdue</span><strong>${a.overdue}</strong></div></div>`;$('#recentActivity').innerHTML=t.slice(0,5).map(x=>`<div class="activity-item"><div class="activity-icon">✓</div><div><strong>${esc(x.title)}</strong><div class="small muted">${esc(x.assignee)} · ${x.progress}% · ${esc(x.status)}</div></div></div>`).join('');renderAdminNotificationManager()}
function adminTaskCard(t){return `<article class="task"><div class="task-top"><div class="task-title">${esc(t.title)}</div>${statusBadge(t.status)}</div><div class="small muted" style="margin-top:6px">${esc(t.description)}</div><div class="meta"><span>${esc(t.assignee)}</span><span>${t.progress}%</span></div><div class="progress"><span style="width:${Math.max(0,Math.min(100,t.progress))}%"></span></div><div class="comments">💬 ${(t.comments||[]).length} update(s) · Due ${esc(t.due||'—')}</div><div class="task-actions"><button class="mini" onclick="editTask(${t.id})">Edit / Reassign</button><button class="mini danger-outline" onclick="deleteTask(${t.id})">Delete</button></div></article>`}
function renderTasks(){const board=$('#adminTaskBoard');if(!board)return;let tasks=getTasks();const q=($('#taskSearch')?.value||'').toLowerCase(),member=$('#taskMemberFilter')?.value||'all';tasks=tasks.filter(t=>(t.title+' '+t.assignee+' '+t.description).toLowerCase().includes(q)&&(member==='all'||t.assignee===member));const groups={assigned:[],ongoing:[],done:[]};tasks.forEach(t=>(groups[t.status]||groups.assigned).push(t));board.innerHTML=['assigned','ongoing','done'].map(s=>`<section class="column"><div class="column-head"><h3>${s[0].toUpperCase()+s.slice(1)}</h3><span class="badge ${s}">${groups[s].length}</span></div>${groups[s].map(adminTaskCard).join('')||'<p class="muted small">No tasks here.</p>'}</section>`).join('');renderStats()}
window.editTask=function(id){const t=getTasks().find(x=>x.id===id);if(!t)return;$('#taskModal').classList.add('open');$('#modalTaskTitle').textContent=t.title;$('#modalTaskId').value=t.id;$('#modalTitle').value=t.title;$('#modalDescription').value=t.description;$('#modalStatus').value=t.status;$('#modalProgress').value=t.progress;$('#modalAssignee').value=t.assignee;$('#modalPriority').value=t.priority;$('#modalDue').value=t.due||'';$('#commentList').innerHTML=(t.comments||[]).map(c=>`<div class="comment">${esc(c)}</div>`).join('')||'<div class="muted small">No updates.</div>'}
window.closeTask=function(){$('#taskModal')?.classList.remove('open')}
window.saveAdminTask=function(){const id=Number($('#modalTaskId').value),tasks=getTasks(),t=tasks.find(x=>x.id===id);if(!t)return;const oldAssignee=t.assignee,oldStatus=t.status,oldProgress=t.progress;t.title=$('#modalTitle').value.trim();t.description=$('#modalDescription').value.trim();t.status=$('#modalStatus').value;t.progress=Math.max(0,Math.min(100,Number($('#modalProgress').value)));t.assignee=$('#modalAssignee').value;t.priority=$('#modalPriority').value;t.due=$('#modalDue').value;const c=$('#newComment').value.trim();if(c)(t.comments||(t.comments=[])).push(`Admin: ${c}`);saveTasks(tasks);addNotification(t.assignee,'Task updated',`Admin updated “${t.title}”. Status: ${t.status}, progress: ${t.progress}%.`,'task');if(oldAssignee!==t.assignee)addNotification(t.assignee,'New task assignment',`You have been assigned “${t.title}”.`,'assignment');if(oldStatus!==t.status||oldProgress!==t.progress)addNotification('admin','Admin task change',`“${t.title}” changed from ${oldStatus}/${oldProgress}% to ${t.status}/${t.progress}%.`,'task');closeTask();renderTasks();toast('Task updated')}
window.deleteTask=function(id){const t=getTasks().find(x=>x.id===id);if(!t||!confirm(`Delete “${t.title}”?`))return;saveTasks(getTasks().filter(x=>x.id!==id));addNotification(t.assignee,'Task removed',`Admin removed “${t.title}” from your task list.`,'task');renderTasks();toast('Task deleted')}
function initTaskPage(){if(!$('#adminTaskBoard'))return;populateMemberSelects();$('#taskSearch')?.addEventListener('input',renderTasks);$('#taskMemberFilter')?.addEventListener('change',renderTasks);renderTasks()}
function populateMemberSelects(){const names=getMembers().map(m=>m.name);$$('[data-member-select]').forEach(sel=>{const current=sel.value;const first=sel.id==='taskMemberFilter'?'<option value="all">All Members</option>':'';sel.innerHTML=first+names.map(n=>`<option>${esc(n)}</option>`).join('');if([...sel.options].some(o=>o.value===current))sel.value=current})}
function initAddTask(){const f=$('#addTaskForm');if(!f)return;populateMemberSelects();f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f),task={id:Date.now(),title:fd.get('title').trim(),description:fd.get('description').trim(),assignee:fd.get('assignee'),status:fd.get('status'),progress:Number(fd.get('progress')||0),priority:fd.get('priority'),due:fd.get('due'),comments:[fd.get('comment')||'Task assigned by admin.']};const tasks=getTasks();tasks.unshift(task);saveTasks(tasks);addNotification(task.assignee,'New task assigned',`Admin assigned you “${task.title}” due ${task.due||'without a due date'}.`,'assignment');toast('Task created and notification sent');f.reset();setTimeout(()=>location.href='tasks.html',450)}}
function renderMembers(){const g=$('#adminMemberGrid');if(!g)return;const members=getMembers(),tasks=getTasks();g.innerHTML=members.map((m,i)=>{const own=tasks.filter(t=>t.assignee===m.name),avg=own.length?Math.round(own.reduce((a,t)=>a+t.progress,0)/own.length):0;return `<article class="panel member-card"><div class="avatar">${m.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2)}</div><h3>${esc(m.name)}</h3><p>${esc(m.role)}</p><p class="small">${esc(m.department)} · ${esc(m.email)}</p><div class="progress" style="margin:14px 0"><span style="width:${avg}%"></span></div><strong>${own.length} task(s) · ${avg}% avg.</strong><div class="task-actions" style="justify-content:center"><button class="mini" onclick="editMember(${i})">Edit</button><button class="mini danger-outline" onclick="removeMember(${i})">Remove</button></div></article>`}).join('')}
window.editMember=function(i){const m=getMembers()[i];if(!m)return;$('#memberModal').classList.add('open');$('#memberIndex').value=i;$('#memberName').value=m.name;$('#memberRole').value=m.role;$('#memberEmail').value=m.email;$('#memberDepartment').value=m.department}
window.closeMember=function(){$('#memberModal')?.classList.remove('open')}
window.saveMember=function(){const i=Number($('#memberIndex').value),members=getMembers(),old=members[i];if(!old)return;const updated={name:$('#memberName').value.trim(),role:$('#memberRole').value.trim(),email:$('#memberEmail').value.trim(),department:$('#memberDepartment').value.trim()};const tasks=getTasks();if(old.name!==updated.name)tasks.forEach(t=>{if(t.assignee===old.name)t.assignee=updated.name});members[i]=updated;saveMembers(members);saveTasks(tasks);const users=getUsers();const user=users.find(x=>x.name===old.name);if(user){user.name=updated.name;user.email=updated.email}saveUsers(users);closeMember();renderMembers();toast('Member updated')}
window.removeMember=function(i){const members=getMembers(),m=members[i];if(!m||!confirm(`Remove ${m.name}? Tasks will stay in the system.`))return;members.splice(i,1);saveMembers(members);const users=getUsers();const userIndex=users.findIndex(x=>x.name===m.name);if(userIndex>-1){users.splice(userIndex,1);saveUsers(users)}renderMembers();toast('Member removed')}
function initAddMember(){const f=$('#addMemberForm');if(!f)return;f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f),m={name:fd.get('name').trim(),role:fd.get('role').trim(),email:fd.get('email').trim(),department:fd.get('department').trim()};const members=getMembers();members.push(m);saveMembers(members);const users=getUsers();const base=normalizeUsername(m.name)||'member';let username=base;let counter=1;while(users.some(u=>u.username===username)){username=`${base}${counter++}`}users.push({username,password:'sync123',name:m.name,role:'Member',email:m.email});saveUsers(users);f.reset();renderMembers();toast('Member added')}}
function renderReports(){const tbody=$('#reportTable');if(!tbody)return;tbody.innerHTML=getTasks().map(t=>`<tr><td>${esc(t.title)}</td><td>${esc(t.assignee)}</td><td>${t.progress}%</td><td>${esc(t.status)}</td><td>${esc(t.priority)}</td><td>${esc(t.due||'—')}</td></tr>`).join('');renderStats();renderReportInsights()}
function renderReportInsights(){const box=$('#reportInsights');if(!box)return;const a=analytics();box.innerHTML=`<div class="analytics-stack"><div class="analytics-card"><span>Average progress</span><strong>${a.avg}%</strong></div><div class="analytics-card"><span>Completion rate</span><strong>${a.total?Math.round(a.done/a.total*100):0}%</strong></div><div class="analytics-card"><span>Open tasks</span><strong>${a.assigned+a.ongoing}</strong></div><div class="analytics-card"><span>Overdue</span><strong>${a.overdue}</strong></div></div>`}
window.exportCSV=function(){const tasks=getTasks();const csv='Task,Assignee,Progress,Status,Priority,Due Date\n'+tasks.map(t=>[t.title,t.assignee,t.progress,t.status,t.priority,t.due].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const b=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='syncboard-admin-report.csv';a.click();URL.revokeObjectURL(a.href)}

function adminRequestStatusBadge(status){const label={pending:'Pending',reviewing:'Reviewing',completed:'Completed',rejected:'Rejected'}[status]||status;return `<span class="request-status ${esc(status)}">${esc(label)}</span>`}
function renderAdminRequests(){const box=$('#adminRequestList');if(!box)return;const filter=$('#requestStatusFilter')?.value||'all',all=getRequests().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)),items=filter==='all'?all:all.filter(r=>r.status===filter);const counts={pending:0,reviewing:0,completed:0,total:all.length};all.forEach(r=>{if(counts[r.status]!==undefined)counts[r.status]++});Object.entries(counts).forEach(([k,v])=>{const el=$(`[data-request-stat="${k}"]`);if(el)el.textContent=v});box.innerHTML=items.length?items.map(r=>`<article class="panel admin-request-card"><div class="request-card-head"><div><div class="request-overline">${esc(r.priority||'Normal')} priority · ${esc(r.category)}</div><h3>${esc(r.memberName)}</h3><div class="small muted">${new Date(r.createdAt).toLocaleString()}${r.taskTitle?` · Task: ${esc(r.taskTitle)}`:''}</div></div>${adminRequestStatusBadge(r.status)}</div><p class="request-message">${esc(r.message)}</p><div class="field"><label>Response / action note</label><textarea id="requestNote-${r.id}" rows="2" placeholder="Optional note sent back to ${esc(r.memberName)}">${esc(r.adminNote||'')}</textarea></div><div class="request-actions"><button class="mini" onclick="updateRequestStatus(${r.id},'reviewing')">Mark Reviewing</button><button class="mini request-complete" onclick="updateRequestStatus(${r.id},'completed')">Complete</button><button class="mini danger-outline" onclick="updateRequestStatus(${r.id},'rejected')">Reject</button></div></article>`).join(''):'<div class="panel empty-note">No requests match this filter.</div>'}
window.updateRequestStatus=function(id,status){const items=getRequests(),r=items.find(x=>x.id===id);if(!r)return;const note=$(`#requestNote-${CSS.escape(String(id))}`)?.value.trim()||'';r.status=status;r.adminNote=note;r.updatedAt=new Date().toISOString();saveRequests(items);const action={reviewing:'is reviewing',completed:'completed',rejected:'declined'}[status]||'updated';addNotification(r.memberName,`Admin request ${status}`,`Admin ${action} your ${r.category.toLowerCase()} request${r.taskTitle?` for “${r.taskTitle}”`:''}.${note?` Response: ${note}`:''}`,'request');renderAdminRequests();renderTopNotifications();toast(`Request marked ${status}`)}
function initAdminRequests(){if(!$('#adminRequestList'))return;$('#requestStatusFilter')?.addEventListener('change',renderAdminRequests);renderAdminRequests()}

function renderAdminNotificationManager(){const box=$('#adminNotificationFeed');if(!box)return;const items=getNotifications();box.innerHTML=items.length?items.slice(0,10).map(n=>`<div class="activity-item"><div class="activity-icon">🔔</div><div><strong>${esc(n.title)}</strong><div class="small muted">To ${esc(n.recipient)} · ${esc(n.message)}</div></div></div>`).join(''):'<div class="muted small">No notifications sent or received yet.</div>'}
function initSendNotification(){const f=$('#sendNotificationForm');if(!f)return;populateNotificationRecipients();f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f);addNotification(fd.get('recipient'),fd.get('title').trim(),fd.get('message').trim(),'admin');f.reset();renderAdminNotificationManager();renderTopNotifications();toast('Notification sent')}}
function populateNotificationRecipients(){const s=$('#notificationRecipient');if(!s)return;s.innerHTML='<option value="all">All members</option>'+getMembers().map(m=>`<option value="${esc(m.name)}">${esc(m.name)}</option>`).join('')}
function initSettings(){const reset=$('#resetData');if(reset)reset.onclick=()=>{if(confirm('Reset SyncBoard tasks, members, notifications and login data to defaults?')){localStorage.removeItem('syncboard-tasks');localStorage.removeItem('syncboard-members');localStorage.removeItem('syncboard-notifications');localStorage.removeItem('syncboard-requests');localStorage.removeItem('syncboard-users');localStorage.removeItem('syncboard-admin-credentials');toast('System data reset');renderAdminSettings()}};$('#saveAdminCredentials')?.addEventListener('click',saveAdminLogin);renderAdminSettings()}
function registerLive(){const c=getChannel();if(c)c.addEventListener('message',()=>{renderDashboard();renderTasks();renderMembers();renderReports();renderAdminNotificationManager();renderTopNotifications();renderAdminRequests()});window.addEventListener('storage',()=>{renderDashboard();renderTasks();renderMembers();renderReports();renderAdminNotificationManager();renderTopNotifications();renderAdminRequests()})}
document.addEventListener('DOMContentLoaded',()=>{applyTheme();initLogin();if(!$('#adminLoginForm')){requireAdmin();initNav();initTopNotifications();registerLive();renderStats();renderDashboard();initTaskPage();initAddTask();renderMembers();initAddMember();renderReports();initSendNotification();initSettings();initAdminRequests()}})
